from erpnext.accounts.doctype.purchase_invoice import purchase_invoice
from erpnext.accounts.doctype.sales_invoice import sales_invoice
from retention_accounting.native_overrides import make_tax_gl_entries_purchase_invoice, make_tax_gl_entries_sales_invoice, get_tax_amount_if_for_valuation_or_deduction, make_gl_entries, make_gl_entries_purchase_invoice
from erpnext.accounts import general_ledger
from erpnext.controllers import taxes_and_totals


# purchase_invoice.PurchaseInvoice.make_tax_gl_entries = make_tax_gl_entries_purchase_invoice
sales_invoice.SalesInvoice.make_tax_gl_entries = make_tax_gl_entries_sales_invoice
taxes_and_totals.calculate_taxes_and_totals.get_tax_amount_if_for_valuation_or_deduction = get_tax_amount_if_for_valuation_or_deduction

# general_ledger.make_gl_entries = make_gl_entries
# purchase_invoice.PurchaseInvoice.make_gl_entries = make_gl_entries_purchase_invoice